print(f'{bool(None) = }')
print(f'{bool(1) = }')
print(f'{bool(0) = }')
print(f'{bool(-1) = }')
print(f'{bool(0.000001) = }')
print(f'{bool(-5.5) = }')
print(f'{bool(0.0) = }')
print(f'{bool("abc") = }')
print(f'{bool(" ") = }')
print(f'{bool("") = }')
print(f'{bool([1, 2]) = }')
print(f'{bool([""]) = }')
print(f'{bool([]) = }')

